version: "2"

services:
  backend:
    image: node:16-alpine
    volumes:
      - ./backend:/srv/app
      - ./frontend/dist:/srv/app/frontend
    working_dir: /srv/app
    command: "npm run dev"
    expose: 
      - "8080"
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true

  frontend:
    image: node:16-alpine
    volumes:
      - ./frontend:/srv/app
    working_dir: /srv/app
    command: "npm run start"
    expose: 
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PROXY_HOST=http://localhost:8080
    tty: true
    stdin_open: true
    depends_on: ["backend"]

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    depends_on: ["backend"]
